"use strict";
/* ====================================================================
   EMBERFORGE DEPTHS — characters & cards
   Three playable characters share the Heat system; each has an
   exclusive card pool plus a small neutral pool ('any').
   ==================================================================== */

/* ---- card value helper: vals can be plain or [base, upgraded] ---- */
function cv(card, key){
  const v = CARD_DEFS[card.def].vals[key];
  return Array.isArray(v) ? v[card.upgraded ? 1 : 0] : v;
}
function makeCard(defId, upgraded){ return { id:'c'+(uid++), def:defId, held:0, upgraded:!!upgraded }; }
function cardDef(card){ return CARD_DEFS[card.def]; }
function cardName(card){ return cardDef(card).name + (card.upgraded ? '⁺' : ''); }

const U = (txt) => `<span class="kw">${txt}</span>`;
function hv(card, key){ /* highlight upgraded values green */
  const v = cv(card, key);
  const arr = CARD_DEFS[card.def].vals[key];
  return (card.upgraded && Array.isArray(arr) && arr[0]!==arr[1]) ? `<b class="upval">${v}</b>` : v;
}

/* ---- keyword glossary (hover tooltips) ---- */
const KEYWORDS = {
  'Chain':    'Triggers if the previous card you played this turn shares this card\'s tag.',
  'Chained':  'Triggers if the previous card you played this turn shares this card\'s tag.',
  'Charge':   'Stays in your hand between turns and grows stronger each turn it is held.',
  'Vent':     'Reduce your current Heat.',
  'Surge':    'Fill your Heat all the way to Capacity.',
  'Exhaust':  'Removed from your deck for the rest of this combat.',
  'Exhausts': 'Removed from your deck for the rest of this combat.',
  'Power':    'A permanent effect for the rest of this combat. Powers are exhausted when played.',
  'Overheat': 'You overheat when Heat exceeds Capacity — each point over sears you for 2 HP, through Block.',
  'Burn':     'Takes damage equal to Burn at the end of its turn, then Burn decays by 1.',
  'Exposed':  'Takes 50% more damage from attacks.',
  'Rattled':  'Deals 25% less damage.',
  'Ignite':   'The target immediately suffers damage equal to its Burn (Burn is not removed).',
  'Servo':    'An automaton that acts at the start of your turn. You can field up to 3.',
  'Servos':   'Automatons that act at the start of your turn. You can field up to 3.',
  'Strength': 'Adds to all attack damage.',
  'Block':    'Absorbs damage. Normally expires at the start of your turn.',
  'Heat':     'Playing cards adds Heat. Exceeding Capacity sears you. Heat resets each turn.',
  'Capacity': 'How much Heat you can hold without overheating.',
  'STRIKE':   'An aggression tag. Play STRIKE after STRIKE to Chain.',
  'GUARD':    'A defense tag. Play GUARD after GUARD to Chain.',
  'ARC':      'A utility tag. Play ARC after ARC to Chain.',
};

/* ====================================================================
   CHARACTERS
   ==================================================================== */
const CHAR_DEFS = {
  forgeborn: {
    name:'The Forgeborn', sprite:'🤖', color:'ember',
    hp:75, cap:9, relic:'bellows',
    title:'Chain-fighter of the Slag Halls',
    blurb:'A war-automaton reawakened in the dead forge. Links STRIKE, GUARD and ARC into relentless chains, and holds Charge cards until they sing.',
    mechanics:'⛓ Chain combos · ⚡ Charge cards',
    deck:['emberJab','emberJab','emberJab','emberJab','ironGuard','ironGuard','ironGuard','stoke','flashVent','flashVent'],
    unlock:null,
  },
  cinderwitch: {
    name:'The Cinderwitch', sprite:'🧙', color:'witch',
    hp:66, cap:10, relic:'pyreLocket',
    title:'Last pyromancer of the Ashen Court',
    blurb:'She does not strike the killing blow — she lights the slow fire that does. Stacks Burn, then Ignites it all at once. Pays for power in blood.',
    mechanics:'🔥 Burn stacking · 🩸 Ignite & sacrifice',
    deck:['sootLash','sootLash','sootLash','sootLash','cinderVeil','cinderVeil','cinderVeil','kindle','immolate','charWard'],
    unlock:'Defeat the Act I boss to unlock',
  },
  scrapwright: {
    name:'The Scrapwright', sprite:'🦾', color:'scrap',
    hp:70, cap:9, relic:'rivetDriver',
    title:'Chief engineer of the Burning Heart',
    blurb:'Never fights alone. Deploys Strike, Aegis and Volt Servos that act every turn — then tunes them, rallies them, or detonates them for scrap.',
    mechanics:'⚙️ Servo squad · 💥 Detonate & salvage',
    deck:['boltThrow','boltThrow','boltThrow','boltThrow','plateUp','plateUp','plateUp','deployStrike','deployAegis','recall'],
    unlock:'Defeat the Act II boss to unlock',
  },
};

/* ---- servo types (Scrapwright) ---- */
const SERVO_DEFS = {
  strike:{icon:'🗡️', name:'Strike Servo', base:4, desc:b=>`Deals ${4+b} damage to a random enemy at the start of your turn.`},
  aegis: {icon:'🛡️', name:'Aegis Servo',  base:4, desc:b=>`Grants ${4+b} Block at the start of your turn.`},
  volt:  {icon:'⚡', name:'Volt Servo',   base:2, desc:b=>`Deals ${2+Math.ceil(b/2)} damage to ALL enemies at the start of your turn.`},
};

/* ====================================================================
   CARDS — tag: STRIKE / GUARD / ARC · target: enemy / none / all
   char: forgeborn / cinderwitch / scrapwright / any
   ==================================================================== */
const CARD_DEFS = {

/* ================= FORGEBORN — STARTERS ================= */
emberJab:{name:'Ember Jab', tag:'STRIKE', target:'enemy', rarity:'starter', char:'forgeborn',
  vals:{cost:3, d:[6,9], cd:[9,13]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Chain:')} deal ${hv(c,'cd')} instead.`,
  play:(c,t,ch)=>dealDamage(t, ch?cv(c,'cd'):cv(c,'d'))},
ironGuard:{name:'Iron Guard', tag:'GUARD', target:'none', rarity:'starter', char:'forgeborn',
  vals:{cost:3, b:[6,9], cb:[9,13]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Chain:')} gain ${hv(c,'cb')} instead.`,
  play:(c,t,ch)=>gainBlock(ch?cv(c,'cb'):cv(c,'b'))},
stoke:{name:'Stoke', tag:'ARC', target:'none', rarity:'starter', char:'forgeborn',
  vals:{cost:[2,1]},
  text:c=>`Gain 3 Capacity this turn. Draw 1 card.`,
  play:()=>{ G.tempCap += 3; drawCards(1); }},
flashVent:{name:'Flash Vent', tag:'GUARD', target:'none', rarity:'starter', char:'forgeborn',
  vals:{cost:0, bonus:[0,3]},
  text:c=>`${U('Vent')} all Heat. Gain Block equal to Heat vented${c.upgraded?' <b class="upval">+3</b>':''}.`,
  play:(c)=>{ const v = G.heat; vent(v); if(v+cv(c,'bonus')>0) gainBlock(v+cv(c,'bonus')); }},

/* ================= CINDERWITCH — STARTERS ================= */
sootLash:{name:'Soot Lash', tag:'STRIKE', target:'enemy', rarity:'starter', char:'cinderwitch',
  vals:{cost:3, d:[5,7], cb:[2,3]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Chain:')} apply ${hv(c,'cb')} ${U('Burn')}.`,
  play:(c,t,ch)=>{ dealDamage(t,cv(c,'d')); if(ch) applyStatus(t,'burn',cv(c,'cb')); }},
cinderVeil:{name:'Cinder Veil', tag:'GUARD', target:'none', rarity:'starter', char:'cinderwitch',
  vals:{cost:3, b:[6,8], cb:[9,12]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Chain:')} gain ${hv(c,'cb')} instead.`,
  play:(c,t,ch)=>gainBlock(ch?cv(c,'cb'):cv(c,'b'))},
kindle:{name:'Kindle', tag:'ARC', target:'enemy', rarity:'starter', char:'cinderwitch',
  vals:{cost:1, burn:[3,5]},
  text:c=>`Apply ${hv(c,'burn')} ${U('Burn')}.`,
  play:(c,t)=>applyStatus(t,'burn',cv(c,'burn'))},
immolate:{name:'Immolate', tag:'STRIKE', target:'enemy', rarity:'starter', char:'cinderwitch',
  vals:{cost:2, mult:[1,2]},
  text:c=>`${U('Ignite:')} the target suffers ${cv(c,'mult')>1?`<b class="upval">double</b> `:''}its ${U('Burn')} immediately.`,
  play:(c,t)=>igniteEnemy(t, cv(c,'mult'))},
charWard:{name:'Char Ward', tag:'GUARD', target:'none', rarity:'starter', char:'cinderwitch',
  vals:{cost:0, v:[2,4]},
  text:c=>`${U('Vent')} ${hv(c,'v')}. Apply 1 ${U('Burn')} to a random enemy.`,
  play:(c)=>{ vent(cv(c,'v')); const alive=G.enemies.filter(e=>e.hp>0); if(alive.length) applyStatus(pick(alive),'burn',1); }},

/* ================= SCRAPWRIGHT — STARTERS ================= */
boltThrow:{name:'Bolt Throw', tag:'STRIKE', target:'enemy', rarity:'starter', char:'scrapwright',
  vals:{cost:3, d:[6,9], cd:[9,13]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Chain:')} deal ${hv(c,'cd')} instead.`,
  play:(c,t,ch)=>dealDamage(t, ch?cv(c,'cd'):cv(c,'d'))},
plateUp:{name:'Plate Up', tag:'GUARD', target:'none', rarity:'starter', char:'scrapwright',
  vals:{cost:3, b:[6,9], cb:[9,13]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Chain:')} gain ${hv(c,'cb')} instead.`,
  play:(c,t,ch)=>gainBlock(ch?cv(c,'cb'):cv(c,'b'))},
deployStrike:{name:'Deploy: Strike Servo', tag:'ARC', target:'none', rarity:'starter', char:'scrapwright',
  vals:{cost:[2,1]},
  text:c=>`Deploy a 🗡️ Strike ${U('Servo')}.<br>${U('Chain:')} it acts immediately.`,
  play:(c,t,ch)=>{ const s = deployServo('strike'); if(ch && s) servoAct(s); }},
deployAegis:{name:'Deploy: Aegis Servo', tag:'ARC', target:'none', rarity:'starter', char:'scrapwright',
  vals:{cost:[2,1]},
  text:c=>`Deploy a 🛡️ Aegis ${U('Servo')}.<br>${U('Chain:')} it acts immediately.`,
  play:(c,t,ch)=>{ const s = deployServo('aegis'); if(ch && s) servoAct(s); }},
recall:{name:'Rally', tag:'ARC', target:'none', rarity:'starter', char:'scrapwright',
  vals:{cost:[1,0]},
  text:c=>`ALL your ${U('Servos')} act immediately.`,
  play:()=>servosAct()},

/* ================= NEUTRAL — COMMON ================= */
deflectPlating:{name:'Deflect Plating', tag:'GUARD', target:'none', rarity:'common', char:'any',
  vals:{cost:1, b:[3,5]},
  text:c=>`Gain ${hv(c,'b')} Block. Draw 1 card.`,
  play:(c)=>{ gainBlock(cv(c,'b')); drawCards(1); }},
coolantRush:{name:'Coolant Rush', tag:'ARC', target:'none', rarity:'common', char:'any',
  vals:{cost:1, v:[5,7], dr:[1,2]},
  text:c=>`${U('Vent')} ${hv(c,'v')}. Draw ${hv(c,'dr')} card${cv(c,'dr')>1?'s':''}.`,
  play:(c)=>{ vent(cv(c,'v')); drawCards(cv(c,'dr')); }},
recklessSpark:{name:'Reckless Spark', tag:'ARC', target:'enemy', rarity:'common', char:'any',
  vals:{cost:0, d:[5,7]},
  text:c=>`Deal ${hv(c,'d')} damage. Add 2 Heat.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); addHeat(2); }},
diagnose:{name:'Diagnose', tag:'ARC', target:'none', rarity:'common', char:'any', exhaust:true,
  vals:{cost:1, dr:[2,3]},
  text:c=>`Draw ${hv(c,'dr')} cards. ${U('Exhaust')}.`,
  play:(c)=>drawCards(cv(c,'dr'))},
magnetPull:{name:'Magnet Pull', tag:'ARC', target:'enemy', rarity:'common', char:'any',
  vals:{cost:1, r:[1,2], cr:[2,3]},
  text:c=>`Apply ${hv(c,'r')} ${U('Rattled')}.<br>${U('Chain:')} apply ${hv(c,'cr')} instead.`,
  play:(c,t,ch)=>applyStatus(t,'rattled', ch?cv(c,'cr'):cv(c,'r'))},

/* ================= NEUTRAL — UNCOMMON ================= */
borrowedTime:{name:'Borrowed Time', tag:'ARC', target:'none', rarity:'uncommon', char:'any',
  vals:{cost:0, dr:[2,3]},
  text:c=>`Draw ${hv(c,'dr')} cards. Start next turn with 3 Heat.`,
  play:(c)=>{ drawCards(cv(c,'dr')); G.pendingHeat += 3; }},
overclock:{name:'Overclock', tag:'ARC', target:'none', rarity:'uncommon', char:'any', power:true,
  vals:{cost:2, n:[3,4]},
  text:c=>`${U('Power:')} gain ${hv(c,'n')} Capacity for the rest of combat.`,
  play:(c)=>{ G.capBonus += cv(c,'n'); log(`Capacity +<span class="hl">${cv(c,'n')}</span>.`); }},
asbestosLining:{name:'Asbestos Lining', tag:'GUARD', target:'none', rarity:'uncommon', char:'any', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} Overheating sears you for 1 less HP per point.`,
  play:()=>{ G.asbestos = true; log('Your seams are insulated.'); }},
temperedMirror:{name:'Tempered Mirror', tag:'GUARD', target:'none', rarity:'uncommon', char:'any',
  vals:{cost:2, plus:[0,4]},
  text:c=>`Gain Block equal to your current Heat${c.upgraded?' <b class="upval">+4</b>':''}.`,
  play:(c)=>gainBlock(G.heat + cv(c,'plus'))},
bastionProtocol:{name:'Bastion Protocol', tag:'GUARD', target:'none', rarity:'uncommon', char:'any',
  vals:{cost:4, b:[14,18]},
  text:c=>`Gain ${hv(c,'b')} Block.`,
  play:(c)=>gainBlock(cv(c,'b'))},

/* ================= NEUTRAL — RARE ================= */
phoenixProtocol:{name:'Phoenix Protocol', tag:'ARC', target:'none', rarity:'rare', char:'any', power:true,
  vals:{cost:3, pct:[25,35]},
  text:c=>`${U('Power:')} the first time you would die this combat, survive with ${hv(c,'pct')}% HP instead.`,
  play:(c)=>{ G.phoenix = Math.max(G.phoenix, cv(c,'pct')); log('Death holds no fear.'); }},
masterSmith:{name:'Master Smith', tag:'ARC', target:'none', rarity:'rare', char:'any', exhaust:true,
  vals:{cost:[3,2]},
  text:c=>`Upgrade ALL cards in your hand for this combat. ${U('Exhaust')}.`,
  play:(c)=>{ G.hand.forEach(h=>{ if(h.id!==c.id) h.upgraded = true; }); log('Your hand gleams, newly forged.'); }},
adamantBulwark:{name:'Adamant Bulwark', tag:'GUARD', target:'none', rarity:'rare', char:'any',
  vals:{cost:3, b:[12,16]},
  text:c=>`Gain ${hv(c,'b')} Block. Block is not lost at the start of next turn.`,
  play:(c)=>{ gainBlock(cv(c,'b')); G.retainBlockNext = true; }},

/* ================= FORGEBORN — COMMON ================= */
twinPistons:{name:'Twin Pistons', tag:'STRIKE', target:'enemy', rarity:'common', char:'forgeborn',
  vals:{cost:3, d:[4,5]},
  text:c=>`Deal ${hv(c,'d')} damage twice.<br>${U('Chain:')} three times.`,
  play:(c,t,ch)=>{ for(let i=0;i<(ch?3:2);i++) if(t.hp>0) dealDamage(t,cv(c,'d')); }},
slagToss:{name:'Slag Toss', tag:'STRIKE', target:'enemy', rarity:'common', char:'forgeborn',
  vals:{cost:2, d:[5,7], burn:[2,3]},
  text:c=>`Deal ${hv(c,'d')} damage. Apply ${hv(c,'burn')} ${U('Burn')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); applyStatus(t,'burn',cv(c,'burn')); }},
pressureStrike:{name:'Pressure Strike', tag:'STRIKE', target:'enemy', rarity:'common', char:'forgeborn',
  vals:{cost:4, plus:[2,6]},
  text:c=>`Deal damage equal to your current Heat +${hv(c,'plus')}.`,
  play:(c,t)=>dealDamage(t, G.heat + cv(c,'plus'))},
cinderFan:{name:'Cinder Fan', tag:'STRIKE', target:'all', rarity:'common', char:'forgeborn',
  vals:{cost:2, d:[4,6]},
  text:c=>`Deal ${hv(c,'d')} damage to ALL enemies.<br>${U('Chain:')} also apply 1 ${U('Burn')} to each.`,
  play:(c,t,ch)=>G.enemies.forEach(e=>{ if(e.hp>0){ dealDamage(e,cv(c,'d')); if(ch&&e.hp>0) applyStatus(e,'burn',1);} })},
pistonKick:{name:'Piston Kick', tag:'STRIKE', target:'enemy', rarity:'common', char:'forgeborn',
  vals:{cost:1, d:[4,6], v:[2,3]},
  text:c=>`Deal ${hv(c,'d')} damage. ${U('Vent')} ${hv(c,'v')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); vent(cv(c,'v')); }},
hammerSwing:{name:'Hammer Swing', tag:'STRIKE', target:'enemy', rarity:'common', char:'forgeborn',
  vals:{cost:3, d:[9,12]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Chain:')} ${U('Vent')} 3.`,
  play:(c,t,ch)=>{ dealDamage(t,cv(c,'d')); if(ch) vent(3); }},
brace:{name:'Brace', tag:'GUARD', target:'none', rarity:'common', char:'forgeborn',
  vals:{cost:2, b:[5,7], cb:[9,12]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Chain:')} gain ${hv(c,'cb')} instead.`,
  play:(c,t,ch)=>gainBlock(ch?cv(c,'cb'):cv(c,'b'))},
shieldRam:{name:'Shield Ram', tag:'GUARD', target:'enemy', rarity:'common', char:'forgeborn',
  vals:{cost:3, n:[5,7], cn:[3,4]},
  text:c=>`Gain ${hv(c,'n')} Block and deal ${hv(c,'n')} damage.<br>${U('Chain:')} +${hv(c,'cn')} to both.`,
  play:(c,t,ch)=>{ const n = cv(c,'n') + (ch?cv(c,'cn'):0); gainBlock(n); dealDamage(t,n); }},
ventGuard:{name:'Vent Guard', tag:'GUARD', target:'none', rarity:'common', char:'forgeborn',
  vals:{cost:2, b:[6,8], v:[2,3]},
  text:c=>`Gain ${hv(c,'b')} Block. ${U('Vent')} ${hv(c,'v')}.`,
  play:(c)=>{ gainBlock(cv(c,'b')); vent(cv(c,'v')); }},
sparkCoil:{name:'Spark Coil', tag:'ARC', target:'all', rarity:'common', char:'forgeborn',
  vals:{cost:1, d:[3,5], cd:[6,8]},
  text:c=>`Deal ${hv(c,'d')} damage to ALL enemies.<br>${U('Chain:')} ${hv(c,'cd')} instead.`,
  play:(c,t,ch)=>G.enemies.forEach(e=>{ if(e.hp>0) dealDamage(e, ch?cv(c,'cd'):cv(c,'d')); })},

/* ================= FORGEBORN — UNCOMMON ================= */
magmaSlam:{name:'Magma Slam', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:5, d:[16,21]},
  text:c=>`Deal ${hv(c,'d')} damage.`,
  play:(c,t)=>dealDamage(t,cv(c,'d'))},
rattlingBlow:{name:'Rattling Blow', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:3, d:[7,10]},
  text:c=>`Deal ${hv(c,'d')} damage. Apply 2 ${U('Rattled')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); applyStatus(t,'rattled',2); }},
capacitorBurst:{name:'Capacitor Burst', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn', charge:true,
  vals:{cost:2, d:[6,8], per:[4,5]},
  text:c=>`Deal ${hv(c,'d')} (+${hv(c,'per')} per turn held) damage.<br>${U('Charge:')} kept in hand at end of turn.`,
  play:(c,t)=>dealDamage(t, cv(c,'d') + cv(c,'per')*(c.held||0))},
cometDriver:{name:'Comet Driver', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:4, d:[12,14], od:[8,10]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Overheat:')} if you overheated this turn, +${hv(c,'od')}.`,
  play:(c,t)=>dealDamage(t, cv(c,'d') + (G.overheatedThisTurn?cv(c,'od'):0))},
chainspark:{name:'Chainspark', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:2, d:[5,8]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Chain:')} draw 1 card and ${U('Vent')} 1.`,
  play:(c,t,ch)=>{ dealDamage(t,cv(c,'d')); if(ch){ drawCards(1); vent(1); } }},
sawblade:{name:'Sawblade', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:3, d:[8,11]},
  text:c=>`Deal ${hv(c,'d')} damage. Apply 1 ${U('Exposed')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); applyStatus(t,'exposed',1); }},
twinComets:{name:'Twin Comets', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:6, d:[11,14]},
  text:c=>`Deal ${hv(c,'d')} damage twice.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); if(t.hp>0) dealDamage(t,cv(c,'d')); }},
storedBulwark:{name:'Stored Bulwark', tag:'GUARD', target:'none', rarity:'uncommon', char:'forgeborn', charge:true,
  vals:{cost:2, b:[4,6], per:[4,5]},
  text:c=>`Gain ${hv(c,'b')} (+${hv(c,'per')} per turn held) Block.<br>${U('Charge:')} kept in hand at end of turn.`,
  play:(c)=>gainBlock(cv(c,'b') + cv(c,'per')*(c.held||0))},
counterweight:{name:'Counterweight', tag:'GUARD', target:'none', rarity:'uncommon', char:'forgeborn',
  vals:{cost:3, b:[8,10], atk:[6,8]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Chain:')} next attack this combat +${hv(c,'atk')} damage.`,
  play:(c,t,ch)=>{ gainBlock(cv(c,'b')); if(ch){ G.nextAtkBonus += cv(c,'atk'); log(`Next attack <span class="hl">+${cv(c,'atk')}</span>.`); } }},
reactiveShell:{name:'Reactive Shell', tag:'GUARD', target:'none', rarity:'uncommon', char:'forgeborn',
  vals:{cost:2, b:[5,7], ob:[8,10]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Overheat:')} if you overheated this turn, +${hv(c,'ob')}.`,
  play:(c)=>gainBlock(cv(c,'b') + (G.overheatedThisTurn?cv(c,'ob'):0))},
exposeSeams:{name:'Expose Seams', tag:'ARC', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:2, x:[2,3]},
  text:c=>`Apply ${hv(c,'x')} ${U('Exposed')}.<br>${U('Chain:')} apply 1 more.`,
  play:(c,t,ch)=>applyStatus(t,'exposed', cv(c,'x')+(ch?1:0))},
scrapCannon:{name:'Scrap Cannon', tag:'ARC', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:2, per:[3,4]},
  text:c=>`Deal ${hv(c,'per')} damage per card played this turn (including this).`,
  play:(c,t)=>dealDamage(t, cv(c,'per') * G.cardsPlayedThisTurn)},
heatSiphon:{name:'Heat Siphon', tag:'ARC', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:2, per:[2,3]},
  text:c=>`${U('Vent')} up to 4 Heat. Deal ${hv(c,'per')} damage per Heat vented.`,
  play:(c,t)=>{ const v = Math.min(4, G.heat); vent(v); if(v>0) dealDamage(t, cv(c,'per')*v); }},
surgeLance:{name:'Surge Lance', tag:'ARC', target:'enemy', rarity:'uncommon', char:'forgeborn',
  vals:{cost:1, per:[3,4]},
  text:c=>`${U('Surge:')} fill Heat to Capacity. Deal ${hv(c,'per')} damage per Heat gained.`,
  play:(c,t)=>{ const gained = Math.max(0, capacity() - G.heat); G.heat = Math.max(G.heat, capacity()); if(gained>0) dealDamage(t, cv(c,'per')*gained); }},
pressureValve:{name:'Pressure Valve', tag:'GUARD', target:'none', rarity:'uncommon', char:'forgeborn', power:true,
  vals:{cost:2, max:[6,9]},
  text:c=>`${U('Power:')} at end of turn, gain Block equal to unspent Capacity (up to ${hv(c,'max')}).`,
  play:(c)=>{ G.valve = Math.max(G.valve, cv(c,'max')); log('Pressure Valve installed.'); }},
quenchTemper:{name:'Quench & Temper', tag:'ARC', target:'none', rarity:'uncommon', char:'forgeborn', power:true,
  vals:{cost:2, s:[2,3]},
  text:c=>`${U('Power:')} gain ${hv(c,'s')} ${U('Strength')}.`,
  play:(c)=>{ G.player.strength += cv(c,'s'); log(`<span class="hl">+${cv(c,'s')} Strength</span>.`); }},

/* ================= FORGEBORN — RARE ================= */
furnaceHeart:{name:'Furnace Heart', tag:'ARC', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:3, d:[4,6]},
  text:c=>`${U('Power:')} at the start of your turn, deal ${hv(c,'d')} damage to ALL enemies.`,
  play:(c)=>{ G.furnace += cv(c,'d'); log('The furnace roars to life.'); }},
conductorsCrown:{name:"Conductor's Crown", tag:'ARC', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} ALL your cards count as ${U('Chained')}.`,
  play:()=>{ G.alwaysChain = true; log('Everything connects.'); }},
meltdown:{name:'Meltdown', tag:'STRIKE', target:'enemy', rarity:'rare', char:'forgeborn',
  vals:{cost:7, d:[30,38]},
  text:c=>`Deal ${hv(c,'d')} damage. (That is a LOT of Heat.)`,
  play:(c,t)=>dealDamage(t,cv(c,'d'))},
heatsinkArray:{name:'Heatsink Array', tag:'GUARD', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} Overheating grants that much Block instead of searing you.`,
  play:()=>{ G.heatsink = true; log('Overheat now converts to Block.'); }},
arcStorm:{name:'Arc Storm', tag:'ARC', target:'all', rarity:'rare', char:'forgeborn',
  vals:{cost:4, d:[4,6]},
  text:c=>`Deal ${hv(c,'d')} damage to ALL enemies twice.<br>${U('Chain:')} three times.`,
  play:(c,t,ch)=>{ for(let i=0;i<(ch?3:2);i++) G.enemies.forEach(e=>{ if(e.hp>0) dealDamage(e,cv(c,'d')); }); }},
perpetualMotion:{name:'Perpetual Motion', tag:'ARC', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} draw 1 additional card each turn.`,
  play:()=>{ G.extraDraw++; log('The gears never stop.'); }},
supernova:{name:'Supernova', tag:'STRIKE', target:'all', rarity:'rare', char:'forgeborn', exhaust:true,
  vals:{cost:5, per:[5,6]},
  text:c=>`${U('Surge:')} fill Heat to Capacity. Deal ${hv(c,'per')} damage per Heat gained to ALL enemies. ${U('Exhaust')}.`,
  play:(c)=>{ const gained = Math.max(0, capacity() - G.heat); G.heat = Math.max(G.heat, capacity());
    if(gained>0) G.enemies.forEach(e=>{ if(e.hp>0) dealDamage(e, cv(c,'per')*gained); }); }},
volcanicRounds:{name:'Volcanic Rounds', tag:'ARC', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} whenever you play a ${U('STRIKE')}, apply 1 ${U('Burn')} to a random enemy.`,
  play:()=>{ G.volcanic = true; log('Your strikes drip with magma.'); }},
resonantBell:{name:'Resonant Bell', tag:'ARC', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} the first card you play each turn triggers twice.`,
  play:()=>{ G.echo = true; log('The bell tolls... twice.'); }},
warRhythm:{name:'War Rhythm', tag:'ARC', target:'none', rarity:'rare', char:'forgeborn', power:true,
  vals:{cost:2, n:[2,3]},
  text:c=>`${U('Power:')} your ${U('STRIKE')} cards deal +${hv(c,'n')} damage.`,
  play:(c)=>{ G.strikeBonus += cv(c,'n'); log(`Your strikes find a rhythm: <span class="hl">+${cv(c,'n')}</span>.`); }},

/* ================= CINDERWITCH — COMMON ================= */
ashfall:{name:'Ashfall', tag:'ARC', target:'all', rarity:'common', char:'cinderwitch',
  vals:{cost:2, b:[1,2], cb:[2,3]},
  text:c=>`Apply ${hv(c,'b')} ${U('Burn')} to ALL enemies.<br>${U('Chain:')} ${hv(c,'cb')} instead.`,
  play:(c,t,ch)=>G.enemies.forEach(e=>{ if(e.hp>0) applyStatus(e,'burn', ch?cv(c,'cb'):cv(c,'b')); })},
searingBrand:{name:'Searing Brand', tag:'STRIKE', target:'enemy', rarity:'common', char:'cinderwitch',
  vals:{cost:2, d:[6,8], bd:[9,12]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>If the target is Burning, deal ${hv(c,'bd')} instead.`,
  play:(c,t)=>dealDamage(t, (t.burn>0)?cv(c,'bd'):cv(c,'d'))},
smolder:{name:'Smolder', tag:'GUARD', target:'none', rarity:'common', char:'cinderwitch',
  vals:{cost:2, b:[5,7]},
  text:c=>`Gain ${hv(c,'b')} Block. Apply 1 ${U('Burn')} to ALL enemies.`,
  play:(c)=>{ gainBlock(cv(c,'b')); G.enemies.forEach(e=>{ if(e.hp>0) applyStatus(e,'burn',1); }); }},
witchlight:{name:'Witchlight', tag:'ARC', target:'none', rarity:'common', char:'cinderwitch',
  vals:{cost:0, hp:[2,1]},
  text:c=>`Lose ${hv(c,'hp')} HP. Draw 2 cards.`,
  play:(c)=>{ selfDamage(cv(c,'hp'), 'Witchlight'); if(G.hp>0) drawCards(2); }},
emberwhip:{name:'Emberwhip', tag:'STRIKE', target:'enemy', rarity:'common', char:'cinderwitch',
  vals:{cost:2, d:[7,9], cb:[2,3]},
  text:c=>`Deal ${hv(c,'d')} damage.<br>${U('Chain:')} apply ${hv(c,'cb')} ${U('Burn')}.`,
  play:(c,t,ch)=>{ dealDamage(t,cv(c,'d')); if(ch && t.hp>0) applyStatus(t,'burn',cv(c,'cb')); }},
flameLick:{name:'Flame Lick', tag:'STRIKE', target:'enemy', rarity:'common', char:'cinderwitch',
  vals:{cost:0, d:[3,5]},
  text:c=>`Deal ${hv(c,'d')} damage. Apply 1 ${U('Burn')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); if(t.hp>0) applyStatus(t,'burn',1); }},
stokePyre:{name:'Stoke the Pyre', tag:'ARC', target:'enemy', rarity:'common', char:'cinderwitch',
  vals:{cost:1, b:[2,3]},
  text:c=>`Apply ${hv(c,'b')} ${U('Burn')}. Draw 1 card.`,
  play:(c,t)=>{ applyStatus(t,'burn',cv(c,'b')); drawCards(1); }},
sootShield:{name:'Soot Shield', tag:'GUARD', target:'none', rarity:'common', char:'cinderwitch',
  vals:{cost:1, b:[4,6]},
  text:c=>`Gain ${hv(c,'b')} Block, +1 per Burning enemy.`,
  play:(c)=>gainBlock(cv(c,'b') + G.enemies.filter(e=>e.hp>0&&e.burn>0).length)},
emberRain:{name:'Ember Rain', tag:'ARC', target:'all', rarity:'common', char:'cinderwitch',
  vals:{cost:3, d:[3,4], b:[1,2]},
  text:c=>`Deal ${hv(c,'d')} damage to ALL enemies and apply ${hv(c,'b')} ${U('Burn')}.`,
  play:(c)=>G.enemies.forEach(e=>{ if(e.hp>0){ dealDamage(e,cv(c,'d')); if(e.hp>0) applyStatus(e,'burn',cv(c,'b')); } })},
quenchVeil:{name:'Quench Veil', tag:'GUARD', target:'none', rarity:'common', char:'cinderwitch',
  vals:{cost:1, b:[3,5], v:[2,3]},
  text:c=>`Gain ${hv(c,'b')} Block. ${U('Vent')} ${hv(c,'v')}.<br>${U('Chain:')} draw 1 card.`,
  play:(c,t,ch)=>{ gainBlock(cv(c,'b')); vent(cv(c,'v')); if(ch) drawCards(1); }},

/* ================= CINDERWITCH — UNCOMMON ================= */
conflagrate:{name:'Conflagrate', tag:'STRIKE', target:'all', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:3, mult:[1,2]},
  text:c=>`${U('Ignite')} ALL enemies${cv(c,'mult')>1?' <b class="upval">twice over</b>':''} — each suffers its ${U('Burn')}.`,
  play:(c)=>igniteAll(cv(c,'mult'))},
bloodOffering:{name:'Blood Offering', tag:'ARC', target:'none', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:0, hp:[3,2]},
  text:c=>`Lose ${hv(c,'hp')} HP. Gain 2 Capacity this turn. Draw 1 card.`,
  play:(c)=>{ selfDamage(cv(c,'hp'), 'Blood Offering'); if(G.hp>0){ G.tempCap += 2; drawCards(1); } }},
pyreDance:{name:'Pyre Dance', tag:'GUARD', target:'none', rarity:'uncommon', char:'cinderwitch', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} whenever you apply ${U('Burn')}, gain 1 Block per application.`,
  play:()=>{ G.pyreDance = true; log('You dance between the flames.'); }},
heartOfAsh:{name:'Heart of Ash', tag:'ARC', target:'none', rarity:'uncommon', char:'cinderwitch', power:true,
  vals:{cost:2, n:[1,2]},
  text:c=>`${U('Power:')} you apply ${U('Burn')} with +${hv(c,'n')}.`,
  play:(c)=>{ G.pyre += cv(c,'n'); log('Your fire deepens.'); }},
witchfireBolt:{name:'Witchfire Bolt', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:3, d:[6,8]},
  text:c=>`Deal ${hv(c,'d')} damage. <b>Double</b> the target's ${U('Burn')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); if(t.hp>0 && t.burn>0){ applyStatus(t,'burn',t.burn); } }},
ashStorm:{name:'Ash Storm', tag:'ARC', target:'all', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:4, d:[4,5], b:[2,3]},
  text:c=>`Deal ${hv(c,'d')} damage to ALL enemies. Apply ${hv(c,'b')} ${U('Burn')} to ALL.`,
  play:(c)=>G.enemies.forEach(e=>{ if(e.hp>0){ dealDamage(e,cv(c,'d')); if(e.hp>0) applyStatus(e,'burn',cv(c,'b')); } })},
soulTithe:{name:'Soul Tithe', tag:'GUARD', target:'none', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:1, hp:3, b:[11,14]},
  text:c=>`Lose 3 HP. Gain ${hv(c,'b')} Block.`,
  play:(c)=>{ selfDamage(3, 'Soul Tithe'); if(G.hp>0) gainBlock(cv(c,'b')); }},
burningHex:{name:'Burning Hex', tag:'ARC', target:'enemy', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:2, b:[3,4], x:[1,2]},
  text:c=>`Apply ${hv(c,'b')} ${U('Burn')} and ${hv(c,'x')} ${U('Exposed')}.`,
  play:(c,t)=>{ applyStatus(t,'burn',cv(c,'b')); applyStatus(t,'exposed',cv(c,'x')); }},
emberHarvest:{name:'Ember Harvest', tag:'ARC', target:'none', rarity:'uncommon', char:'cinderwitch',
  vals:{cost:1, max:[2,3]},
  text:c=>`Draw 1 card and ${U('Vent')} 2 per Burning enemy (max ${hv(c,'max')} enemies).`,
  play:(c)=>{ const n = Math.min(cv(c,'max'), G.enemies.filter(e=>e.hp>0&&e.burn>0).length);
    if(n>0){ drawCards(n); vent(2*n); } }},
feverPitch:{name:'Fever Pitch', tag:'ARC', target:'none', rarity:'uncommon', char:'cinderwitch', power:true,
  vals:{cost:2, b:[2,3]},
  text:c=>`${U('Power:')} at the start of your turn, apply ${hv(c,'b')} ${U('Burn')} to a random enemy.`,
  play:(c)=>{ G.feverPitch += cv(c,'b'); log('The fever takes hold.'); }},

/* ================= CINDERWITCH — RARE ================= */
inferno:{name:'Inferno', tag:'ARC', target:'none', rarity:'rare', char:'cinderwitch', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} at the end of your turn, ${U('Ignite')} ALL enemies.`,
  play:()=>{ G.igniteEnd = true; log('The deep fire answers your call.'); }},
sacrificialRite:{name:'Sacrificial Rite', tag:'ARC', target:'none', rarity:'rare', char:'cinderwitch', exhaust:true,
  vals:{cost:1, hp:[5,3]},
  text:c=>`Lose ${hv(c,'hp')} HP. Gain 2 ${U('Strength')}. Draw 2 cards. ${U('Exhaust')}.`,
  play:(c)=>{ selfDamage(cv(c,'hp'), 'Sacrificial Rite'); if(G.hp>0){ G.player.strength += 2; drawCards(2); log('<span class="hl">+2 Strength</span>.'); } }},
worldfire:{name:'Worldfire', tag:'STRIKE', target:'all', rarity:'rare', char:'cinderwitch',
  vals:{cost:5, b:[4,6]},
  text:c=>`Apply ${hv(c,'b')} ${U('Burn')} to ALL enemies. Then ${U('Ignite')} ALL.`,
  play:(c)=>{ G.enemies.forEach(e=>{ if(e.hp>0) applyStatus(e,'burn',cv(c,'b')); }); igniteAll(1); }},
ashRebirth:{name:'Ash Rebirth', tag:'ARC', target:'none', rarity:'rare', char:'cinderwitch', exhaust:true,
  vals:{cost:2, max:[12,18]},
  text:c=>`Heal HP equal to the total ${U('Burn')} on all enemies (max ${hv(c,'max')}). ${U('Exhaust')}.`,
  play:(c)=>{ const tot = G.enemies.filter(e=>e.hp>0).reduce((s,e)=>s+(e.burn||0),0);
    const h = Math.min(cv(c,'max'), tot); if(h>0){ heal(h); log(`You drink the fire: heal <span class="hl">${h}</span>.`); } }},
cinderCrown:{name:'Cinder Crown', tag:'ARC', target:'none', rarity:'rare', char:'cinderwitch', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} ${U('Burn')} you apply +1. When an enemy dies, apply 4 ${U('Burn')} to ALL enemies.`,
  play:()=>{ G.pyre += 1; G.cinderCrown = true; log('A crown of embers settles on your brow.'); }},
everburn:{name:'Everburn', tag:'ARC', target:'none', rarity:'rare', char:'cinderwitch', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} enemy ${U('Burn')} no longer decays.`,
  play:()=>{ G.emberseal = true; log('What burns, burns forever.'); }},

/* ================= SCRAPWRIGHT — COMMON ================= */
rivetGun:{name:'Rivet Gun', tag:'STRIKE', target:'enemy', rarity:'common', char:'scrapwright',
  vals:{cost:2, d:[4,5]},
  text:c=>`Deal ${hv(c,'d')} damage twice.<br>${U('Chain:')} your Strike ${U('Servos')} act.`,
  play:(c,t,ch)=>{ for(let i=0;i<2;i++) if(t.hp>0) dealDamage(t,cv(c,'d'));
    if(ch) G.servos.filter(s=>s.type==='strike').forEach(s=>servoAct(s)); }},
scrapShot:{name:'Scrap Shot', tag:'STRIKE', target:'enemy', rarity:'common', char:'scrapwright',
  vals:{cost:1, d:[4,6], per:[2,3]},
  text:c=>`Deal ${hv(c,'d')} damage, +${hv(c,'per')} per deployed ${U('Servo')}.`,
  play:(c,t)=>dealDamage(t, cv(c,'d') + cv(c,'per')*G.servos.length)},
buttress:{name:'Buttress', tag:'GUARD', target:'none', rarity:'common', char:'scrapwright',
  vals:{cost:2, b:[5,7], per:[2,3]},
  text:c=>`Gain ${hv(c,'b')} Block, +${hv(c,'per')} per deployed ${U('Servo')}.`,
  play:(c)=>gainBlock(cv(c,'b') + cv(c,'per')*G.servos.length)},
quickFix:{name:'Quick Fix', tag:'GUARD', target:'none', rarity:'common', char:'scrapwright',
  vals:{cost:1, b:[4,6]},
  text:c=>`Gain ${hv(c,'b')} Block. Draw 1 card.`,
  play:(c)=>{ gainBlock(cv(c,'b')); drawCards(1); }},
lobGrenade:{name:'Lob Grenade', tag:'STRIKE', target:'all', rarity:'common', char:'scrapwright',
  vals:{cost:2, d:[4,5], cd:[6,8]},
  text:c=>`Deal ${hv(c,'d')} damage to ALL enemies.<br>${U('Chain:')} ${hv(c,'cd')} instead.`,
  play:(c,t,ch)=>G.enemies.forEach(e=>{ if(e.hp>0) dealDamage(e, ch?cv(c,'cd'):cv(c,'d')); })},
spotWeld:{name:'Spot Weld', tag:'GUARD', target:'none', rarity:'common', char:'scrapwright',
  vals:{cost:2, b:[7,9], h:[2,3]},
  text:c=>`Gain ${hv(c,'b')} Block.<br>${U('Chain:')} repair ${hv(c,'h')} HP.`,
  play:(c,t,ch)=>{ gainBlock(cv(c,'b')); if(ch) heal(cv(c,'h')); }},
powerFeed:{name:'Power Feed', tag:'ARC', target:'none', rarity:'common', char:'scrapwright',
  vals:{cost:1, v:[3,4], cvt:[5,7]},
  text:c=>`${U('Vent')} ${hv(c,'v')}. Draw 1 card.<br>${U('Chain:')} ${U('Vent')} ${hv(c,'cvt')} instead.`,
  play:(c,t,ch)=>{ vent(ch?cv(c,'cvt'):cv(c,'v')); drawCards(1); }},
jumpStart:{name:'Jump Start', tag:'ARC', target:'none', rarity:'common', char:'scrapwright',
  vals:{cost:0, dr:[2,3]},
  text:c=>`Add 2 Heat. Draw ${hv(c,'dr')} cards.`,
  play:(c)=>{ addHeat(2); drawCards(cv(c,'dr')); }},
deployVolt:{name:'Deploy: Volt Servo', tag:'ARC', target:'none', rarity:'common', char:'scrapwright',
  vals:{cost:[2,1]},
  text:c=>`Deploy a ⚡ Volt ${U('Servo')}.<br>${U('Chain:')} it acts immediately.`,
  play:(c,t,ch)=>{ const s = deployServo('volt'); if(ch && s) servoAct(s); }},

/* ================= SCRAPWRIGHT — UNCOMMON ================= */
tuneUp:{name:'Tune-Up', tag:'ARC', target:'none', rarity:'uncommon', char:'scrapwright',
  vals:{cost:2, n:[2,3]},
  text:c=>`Your ${U('Servos')} gain +${hv(c,'n')} power for the rest of combat.`,
  play:(c)=>{ G.servoBoost += cv(c,'n'); log(`Servos hum at <span class="hl">+${G.servoBoost}</span> power.`); renderCombat(); }},
detonateServo:{name:'Detonate Servo', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'scrapwright',
  vals:{cost:1, d:[13,17], alt:[4,6]},
  text:c=>`Destroy your newest ${U('Servo')}: deal ${hv(c,'d')} damage.<br>If you have none, deal ${hv(c,'alt')} instead.`,
  play:(c,t)=>{ if(G.servos.length){ destroyServo(); dealDamage(t, cv(c,'d')); } else dealDamage(t, cv(c,'alt')); }},
salvageBurst:{name:'Salvage Burst', tag:'ARC', target:'none', rarity:'uncommon', char:'scrapwright',
  vals:{cost:0, dr:[3,4]},
  text:c=>`Destroy your newest ${U('Servo')}: draw ${hv(c,'dr')} cards and ${U('Vent')} 3.<br>If you have none, draw 1.`,
  play:(c)=>{ if(G.servos.length){ destroyServo(); drawCards(cv(c,'dr')); vent(3); } else drawCards(1); }},
rallyCommand:{name:'Rally Command', tag:'ARC', target:'none', rarity:'uncommon', char:'scrapwright',
  vals:{cost:[2,1]},
  text:c=>`ALL your ${U('Servos')} act.<br>${U('Chain:')} they act twice.`,
  play:(c,t,ch)=>{ servosAct(); if(ch) servosAct(); }},
assemblyLine:{name:'Assembly Line', tag:'ARC', target:'none', rarity:'uncommon', char:'scrapwright',
  vals:{cost:[3,2]},
  text:c=>`Deploy a copy of a random deployed ${U('Servo')} (a 🗡️ Strike Servo if you have none).`,
  play:()=>deployServo(G.servos.length ? pick(G.servos).type : 'strike')},
shieldBattery:{name:'Shield Battery', tag:'GUARD', target:'none', rarity:'uncommon', char:'scrapwright',
  vals:{cost:1, per:[3,4]},
  text:c=>`Gain ${hv(c,'per')} Block per deployed ${U('Servo')}.`,
  play:(c)=>gainBlock(cv(c,'per')*G.servos.length)},
magnetHarpoon:{name:'Magnet Harpoon', tag:'STRIKE', target:'enemy', rarity:'uncommon', char:'scrapwright',
  vals:{cost:2, d:[7,9]},
  text:c=>`Deal ${hv(c,'d')} damage. Apply 2 ${U('Rattled')}.`,
  play:(c,t)=>{ dealDamage(t,cv(c,'d')); if(t.hp>0) applyStatus(t,'rattled',2); }},
sentryProtocol:{name:'Sentry Protocol', tag:'GUARD', target:'none', rarity:'uncommon', char:'scrapwright', power:true,
  vals:{cost:2, per:[2,3]},
  text:c=>`${U('Power:')} at the end of your turn, gain ${hv(c,'per')} Block per deployed ${U('Servo')}.`,
  play:(c)=>{ G.sentryBlock += cv(c,'per'); log('Sentry protocol engaged.'); }},
fieldRepair:{name:'Field Repair', tag:'GUARD', target:'none', rarity:'uncommon', char:'scrapwright', exhaust:true,
  vals:{cost:2, h:[5,7], b:[5,7]},
  text:c=>`Repair ${hv(c,'h')} HP. Gain ${hv(c,'b')} Block. ${U('Exhaust')}.`,
  play:(c)=>{ heal(cv(c,'h')); gainBlock(cv(c,'b')); }},
haulerFrame:{name:'Hauler Frame', tag:'ARC', target:'none', rarity:'uncommon', char:'scrapwright', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} you can field 1 additional ${U('Servo')} (max 4).`,
  play:()=>{ G.servoCap = Math.min(4, G.servoCap+1); log('Your frame can carry one more.'); renderCombat(); }},

/* ================= SCRAPWRIGHT — RARE ================= */
overdriveEngine:{name:'Overdrive Engine', tag:'ARC', target:'none', rarity:'rare', char:'scrapwright', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} your ${U('Servos')} act twice each turn.`,
  play:()=>{ G.servoTwice = true; log('The engines scream in overdrive.'); }},
omegaFrame:{name:'Omega Frame', tag:'ARC', target:'none', rarity:'rare', char:'scrapwright', exhaust:true,
  vals:{cost:[4,3]},
  text:c=>`Fill all empty ${U('Servo')} slots with random Servos. ${U('Exhaust')}.`,
  play:()=>{ let guard = 8; while(G.servos.length < G.servoCap && guard-- > 0) deployServo(pick(['strike','aegis','volt'])); }},
fabricator:{name:'Fabricator', tag:'ARC', target:'none', rarity:'rare', char:'scrapwright', power:true,
  vals:{cost:[3,2]},
  text:c=>`${U('Power:')} at the start of your turn, deploy a random ${U('Servo')} if you have an empty slot.`,
  play:()=>{ G.fabricator = true; log('The fabricator whirs to life.'); }},
payloadDelivery:{name:'Payload Delivery', tag:'STRIKE', target:'all', rarity:'rare', char:'scrapwright',
  vals:{cost:4, base:[8,10], per:[7,9]},
  text:c=>`Destroy ALL your ${U('Servos')}. Deal ${hv(c,'base')} +${hv(c,'per')} per Servo destroyed to ALL enemies.`,
  play:(c)=>{ const n = G.servos.length; for(let i=0;i<n;i++) destroyServo();
    const dmg = cv(c,'base') + cv(c,'per')*n;
    G.enemies.forEach(e=>{ if(e.hp>0) dealDamage(e, dmg); }); }},
primeDirective:{name:'Prime Directive', tag:'ARC', target:'none', rarity:'rare', char:'scrapwright', power:true,
  vals:{cost:[2,1]},
  text:c=>`${U('Power:')} ${U('Servos')} also act when deployed.`,
  play:()=>{ G.primeDirective = true; log('Directive accepted: immediate engagement.'); }},
bulwarkColossus:{name:'Bulwark Colossus', tag:'GUARD', target:'none', rarity:'rare', char:'scrapwright',
  vals:{cost:3, b:[12,16]},
  text:c=>`Gain ${hv(c,'b')} Block. Deploy an 🛡️ Aegis ${U('Servo')}.`,
  play:(c)=>{ gainBlock(cv(c,'b')); deployServo('aegis'); }},

/* ================= STATUS / CURSE ================= */
slag:{name:'Slag', tag:'STATUS', target:'none', rarity:'status', char:'none', unplayable:true,
  vals:{cost:0},
  text:()=>`Unplayable. ${U('Exhausts')} at end of turn.`, play:()=>{}},
heavySoot:{name:'Heavy Soot', tag:'CURSE', target:'none', rarity:'curse', char:'none', unplayable:true,
  vals:{cost:0},
  text:()=>`Unplayable. It clings to everything.`, play:()=>{}},
crackedCore:{name:'Cracked Core', tag:'CURSE', target:'none', rarity:'curse', char:'none', unplayable:true,
  vals:{cost:0},
  text:()=>`Unplayable. At end of turn, if in hand, take 2 damage.`, play:()=>{}},
};

/* ====================================================================
   REWARD POOLS — built per character from CARD_DEFS
   ==================================================================== */
function rewardPool(rarity, charId){
  const who = charId || (G && G.character) || 'forgeborn';
  return Object.keys(CARD_DEFS).filter(id=>{
    const d = CARD_DEFS[id];
    return d.rarity === rarity && (d.char === 'any' || d.char === who);
  });
}
function rollRewardCards(n, elite){
  const out = [], used = new Set();
  let guard = 0;
  while(out.length < n && guard++ < 200){
    const r = randf();
    let pool;
    if(elite) pool = r < .40 ? 'uncommon' : (r < .72 ? 'rare' : 'common');
    else pool = r < .58 ? 'common' : (r < .92 ? 'uncommon' : 'rare');
    const id = pick(rewardPool(pool));
    if(used.has(id)) continue;
    used.add(id); out.push(id);
  }
  return out;
}
function randomCardOfRarity(rarity){ return pick(rewardPool(rarity)); }
